### ISSUE TITLE
Before this worked on termux but not today... (I reinstalled everything)

### ISSUE THREAD

**Issue by sayantan300** [atlx/discord-term#79]

**Comment by cloudrex** [comment]
Hey! Have you tried installing previous versions of the NPM package?

**Comment by sayantan300** [comment]
No

**Comment by sayantan300** [comment]
How can I do that?

**Comment by sayantan300** [comment]
Even building didn't work

**Comment by cloudrex** [comment]
Like this:

```
> npm i discord-term@1.2.2
```

Take a look at the [version history on NPM here](https://www.npmjs.com/package/discord-term?activeTab=versions).

**Comment by atlx** [comment]
As an alternative, you can also try building and installing this project manually, from this GitHub repository.

**Comment by kdev** [comment]
@sayantan300, is this still an error? If not please close this issue.

**Comment by sayantan300** [comment]
Uh ok
