### ISSUE TITLE
dterm just freezes after /login

### ISSUE THREAD

**Issue by legop3** [atlx/discord-term#86]
hello. i am slowly transitioning to using only CLI programs, and this one isnt working.

when i type "/login (token)" it just freezes, the cursor stops blinking, and i have to close the terminal because it never comes back. i am using a bot token, and my bot is in a server already.

EDIT: it actually freezes after typing /help too so maybe there is something wrong with my installation

**Comment by atlx** [comment]
@legop3 Try building and installing it from this GitHub repository!

**Comment by legop3** [comment]
oh! i overlooked the fact that it doesnt work over SSH. it all works fine on ubuntu terminal though so no worries.
